on:
  push:
    paths:
    - 'workflows/rg.orchestrator.yml'
  workflow_dispatch: {}
    inputs:
      project_n:
        type: string
        description: 'The name of the project'
        required: true
      location_1:
        type: choice
        description: 'The main region'
        options:
        - eastus
        - eastus2
        - westus
        - westus3
      location_2:
        type: choice
        description: 'The paired region'
        options:
        - eastus
        - eastus2
        - westus
        - westus3

jobs:
  deploy-dev-rg:
  environment: dev
  runs-on: ubuntu-latest
  steps:

  # Log into Azure
  - name: Login to Azure
    uses: azure/login@v1
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }}

  - name: Create RG
    uses: azure/CLI@v1
    with:
      azcliversion: 2.37.0
      inlineScript: |
        az group create \
        --subscription ${{ secrets.SUB_ID }} \
        --name "rg-${{ github.event.inputs.project_n }}-${{ github.event.inputs.location_1 }}-dev" \
        --location ${{ github.event.inputs.location_1 }}