name: Deploy Az RGs for a given project

on:
  workflow_dispatch:
    inputs:
      project_n:
        type: string
        description: 'The name of the project'
        required: true
      location_1:
        type: choice
        description: 'The main region'
        required: true
        options:
        - eastus
        - eastus2
        - westus
        - westus3
        - centralus
      location_2:
        type: choice
        description: 'The paired region'
        options:
        - eastus2
        - centralus
        - westus
        - eastus
        - westus3

jobs:
  deploy-dev-rg:
    environment: dev
    runs-on: ubuntu-latest
    steps:

    # Log into Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create RG
    - name: Create RG
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
          az group create \
          --subscription ${{ secrets.SUB_ID }} \
          --name "rg-${{ inputs.project_n }}-dev-${{ inputs.location_1 }}" \
          --location ${{ inputs.location_1 }}

  deploy-qa-rg:
    environment: qa
    runs-on: ubuntu-latest
    steps:

    # Log into Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create RG
    - name: Create RG
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
          az group create \
          --subscription ${{ secrets.SUB_ID }} \
          --name "rg-${{ inputs.project_n }}-qa-${{ inputs.location_1 }}" \
          --location ${{ inputs.location_1 }}

  deploy-stg-rg:
    environment: stg
    runs-on: ubuntu-latest
    steps:

    # Log into Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create RG Region 1
    - name: Create RG
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
          az group create \
          --subscription ${{ secrets.SUB_ID }} \
          --name "rg-${{ inputs.project_n }}-stg-${{ inputs.location_1 }}" \
          --location ${{ inputs.location_1 }}

    # Create RG Region 2
    - name: Create RG
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
          az group create \
          --subscription ${{ secrets.SUB_ID }} \
          --name "rg-${{ inputs.project_n }}-stg-${{ inputs.location_2 }}" \
          --location ${{ inputs.location_2 }}

  deploy-prod-rg:
    environment: prod
    runs-on: ubuntu-latest
    steps:

    # Log into Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Create RG Region 1
    - name: Create RG
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
          az group create \
          --subscription ${{ secrets.SUB_ID }} \
          --name "rg-${{ inputs.project_n }}-prod-${{ inputs.location_1 }}" \
          --location ${{ inputs.location_1 }}

    # Create RG Region 2
    - name: Create RG
      uses: azure/CLI@v1
      with:
        azcliversion: 2.37.0
        inlineScript: |
          az group create \
          --subscription ${{ secrets.SUB_ID }} \
          --name "rg-${{ inputs.project_n }}-prod-${{ inputs.location_2 }}" \
          --location ${{ inputs.location_2 }}
